var Caged = [{
    "unit":636,
    "show_id":643557,
    "show_title":"It Could Happen to You",
    "release_year":"1994","rating":"3.4",
    "category":"Comedies",
    "show_cast":"Nicolas Cage, Bridget Fonda, Rosie P\u00e9rez, Wendell Pierce, Isaac Hayes, V\u00edctor Rojas, Seymour Cassel, Stanley Tucci, J.E. Freeman",
    "director":"Andrew Bergman",
    "summary":"In this charming romantic comedy based on a true story, a coffee-shop waitress gets a life-changing tip when a beat cop comes up short on pocket change and promises her half of his potential winnings from a lottery ticket.","poster":"http:\/\/netflixroulette.net\/api\/posters\/643557.jpg",
    "mediatype":0,
    "runtime":"101 min"
    },
    { "unit": 800,
    "show_id":70143241,
    "show_title":"The Croods",
    "release_year":"2013",
    "rating":"4.1",
    "category":"Children & Family Movies",
    "show_cast":"Nicolas Cage, Emma Stone, Ryan Reynolds, Catherine Keener, Cloris Leachman, Clark Duke, Chris Sanders, Randy Thom",
    "director":"Kirk De Micco, Chris Sanders",
    "summary":"When an earthquake obliterates their cave, an unworldly prehistoric family is forced to journey through unfamiliar terrain in search of a new home. But things for pessimistic dad Grug go from bad to worse when his daughter meets a clever cave boy.",
    "poster":"http:\/\/netflixroulette.net\/api\/posters\/70143241.jpg",
    "mediatype":0,
    "runtime":"98 min"
    },
    {"unit":2651,
    "show_id":70131173,
    "show_title":"Christmas Carol: The Movie",
    "release_year":"2001","rating":"3.5",
    "category":"Children & Family Movies",
    "show_cast":"Simon Callow, Rhys Ifans, Kate Winslet, Nicolas Cage, Jane Horrocks, Michael Gambon, Juliet Stevenson, Robert Llewellyn, Iain Jones, Colin McFarlane",
    "director":"Jimmy T. Murakami",
    "summary":"Nicolas Cage, Kate Winslet and Simon Callow provide voices for this animated version of the classic Charles Dickens tale about the miserable Ebenezer Scrooge, who learns the true meaning of Christmas from three ghosts who confront him in the night. The film uses live-action sequences to bookend the story, and a mouse in the animated portion helps younger viewers follow the story. Winslet sings the film's main theme.",
    "poster":"http:\/\/netflixroulette.net\/api\/posters\/70131173.jpg",
    "mediatype":0,
    "runtime":"77 min"},
    {"unit":3863,
    "show_id":70257818,
    "show_title":"Stolen",
    "release_year":"2012",
    "rating":"3.7",
    "category":"Action & Adventure",
    "show_cast":"Nicolas Cage, Josh Lucas, Danny Huston, Malin Akerman, Sami Gayle, Edrick Browne, Mark Valley, Barry Shabaka Henley, M.C. Gainey",
    "director":"Simon West",
    "summary":"Master thief Will Montgomery is ready to leave his criminal past behind. But when his daughter is kidnapped, he has no choice but to reunite with his old partner in crime and pull off one last heist.",
    "poster":"http:\/\/netflixroulette.net\/api\/posters\/70257818.jpg",
    "mediatype":0,
    "runtime":"96 min"
    },
    {"unit":5221,
    "show_id":70135880,
    "show_title":"Seeking Justice",
    "release_year":"2011",
    "rating":"3.8",
    "category":"Action & Adventure",
    "show_cast":"Nicolas Cage, January Jones, Guy Pearce, Harold Perrineau, Jennifer Carpenter, Xander Berkeley, IronE Singleton, Wayne P\u00e9re, Marcus Lyle Brown, Jason Davis",
    "director":"Roger Donaldson",
    "summary":"After his wife is brutally raped, English teacher Will Gerard is approached by a man from a vigilante group who offers to exact revenge on the perpetrator. But once the deed is done, Will discovers that the group expects a certain favor in return.",
    "poster":"http:\/\/netflixroulette.net\/api\/posters\/70135880.jpg",
    "mediatype":0,
    "runtime":"105 min"
    },
    {"unit":6000,
    "show_id":70206627,
    "show_title":"Trespass",
    "release_year":"2011",
    "rating":"3.5",
    "category":"Thrillers",
    "show_cast":"Nicolas Cage, Nicole Kidman, Ben Mendelsohn, Liana Liberato, Cam Gigandet, Jordana Spiro, Dash Mihok, Emily Meade, Nico Tortorella, Brandon Belknap",
    "director":"Joel Schumacher",
    "summary":"A husband and wife find themselves pushed to their absolute limit when they're held for ransom by brutal thugs who invade their home. As tensions escalate and shocking revelations emerge, the couple is forced to take ever-more desperate measures.",
    "poster":"http:\/\/netflixroulette.net\/api\/posters\/70206627.jpg",
    "mediatype":0,
    "runtime":"91 min"},
    {"unit":8054,
    "show_id":70253159,
    "show_title":"Frozen Ground",
    "release_year":"2013",
    "rating":"3.4",
    "category":"Thrillers",
    "poster":"http:\/\/netflixroulette.net\/api\/posters\/692295.jpg",
    "mediatype":0,
    "runtime":"N\/A"
    }
]